name: iati-dev-registry

services:
  crmdb:
    container_name: iati-dev-crm-db
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: aWWGhZeedjI20XWv
      MARIADB_DATABASE: suitecrm
      MARIADB_USER: suitecrm_admin
      MARIADB_PASSWORD: saO7tXCBTsxDjcz1
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 2s
      timeout: 60s
      retries: 10
    volumes:
      - crm_db_data:/var/lib/mysql/"

  crm:
    container_name: iati-dev-crm
    build:
      context: ./suitecrm/
      args:
        USERID: ${IATI_CRM_LOCALDEV_USERID}
        GROUPID: ${IATI_CRM_LOCALDEV_GROUPID}
    ports:
      - 8080:80
    volumes:
      - ${IATI_CRM_PATH}:/var/www/html
      - ./suitecrm/config_si.php:/var/www/html/config_si.php
      - ./suitecrm/private.key:/var/www/html/Api/V8/OAuth2/private.key
      - ./suitecrm/public.key:/var/www/html/Api/V8/OAuth2/public.key
    depends_on:
      crmdb:
        condition: service_healthy

volumes:
  crm_db_data:
    driver: local

